version = 1

[[annotations]]
path = [ "original/FingerprintIcon.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Solitudinem"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/GoogleIcons.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Jeffrey Christopher"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/HappyStar.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Natalia Świerz"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/HeartMedical.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Sarpreet Kalyan"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/SurprisedBoy.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Hizen"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/USAMapWithOutlines.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Marina Trajkovska"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/UserAuthentication.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Musa Adanur"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/UserInteractionAnimation.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Mahendra Bhunwal"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"

[[annotations]]
path = [ "original/UserInterface.json" ]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2025 Bashir Ahmad"
SPDX-License-Identifier = "LicenseRef-Lottie-Simple-License-9.13.21"
